### ISSUE TITLE
[4.13.0] AttributeError: type object 'PytestDjangoTestCase' has no attribute '_pre_setup_ran_eagerly'

### ISSUE THREAD

**Issue by sobolevn** [pytest-dev/pytest-django#1303]
After upgrading from 4.12.0 I got a regression, now 395 of my tests fail with:

```
[3](https://github.com/wemake-services/django-modern-rest/actions/runs/31078669060/job/92542226654?pr=1215#step:7:6294)
ERROR tests/test_unit/test_security/test_token/test_app/test_token_model.py::test_acreate_token_without_expiry - AttributeError: type object 'PytestDjangoTestCase' has no attribute '_pre_setup_ran_eagerly'
```

https://github.com/wemake-services/django-modern-rest/actions/runs/31078669060/job/92542226654?pr=1215

This is Django version specific: only tests with Django 5.0 and Django 5.1 fail.
I see that the official support was dropped, but maybe we can still fix it? 
Packages that still support older Django versions would need either to stay on the older package version or to also drop older versions.

Will changing `if not PytestDjangoTestCase._pre_setup_ran_eagerly:` to `if not getattr(PytestDjangoTestCase, '_pre_setup_ran_eagerly', False):` solve it?

**Comment by bluetech** [comment]
I figure the main reason why such a problem happens is that pytest-djagno doesn't actually depend on django. This is intentional, however if it *did* depend on Django, it can then specify `django>=5.2`, and then projects which depend on e.g. `django==5.1` and `pytest-django` will automatically get a compatible version of pytest-django (the resolver should take care of that).

I still don't want to add the dependency, but maybe we can add an optional extra, e.g. `pytest-django[django]`, and recommend projects to use that if they want to ensure compatible resolve. If Python ever gets [default extras](https://peps.python.org/pep-0771/), we can switch it to be a default.

---

Well all of that wouldn't help your current issue because 4.13.0 is already released. So if this causes a real issue for you, I'll be willing to accept a PR for it, and I will add the extra for the next times.

**Comment by selfhoster1312** [comment]
Faced the same issue. In my opinion, the problem is not that 4.2 LTS was deprecated (it was EOL after all), but that pytest-django didn't respect semver. I believe a proper fix would be to revert 4.13, and release 5.0 with the new major django dependency.

In the meantime, i pinned pytest-django to 4.12.

Thank you maintainers for your hard work.

**Comment by bluetech** [comment]
> pytest-django didn't respect semver. I believe a proper fix would be to revert 4.13, and release 5.0 with the new major django dependency.

I believe it is accepted practice not to bump major when dropping support for old Python or Django versions. As I said, I think the main issue is that in the current setup, we don't have the dependency resolver's help (we do for Python versions, but not for Django versions).

**Comment by sobolevn** [comment]
@bluetech PR is on its way, thank you :)

**Comment by bluetech** [comment]
Released 4.14.0.

**Comment by ulgens** [comment]
> still don't want to add the dependency

Is there any background info on this? My understand is that this package always needs Django, which means it's actually a dependency.

**Comment by bluetech** [comment]
> My understand is that this package always needs Django

If django is not installed, the plugin does nothing.

There are cases where pytest-django may end up getting installed, e.g. as a dev dependency in a mono repo or whatever, but it's not a django project. It seems good to me to not force django via a dev dependency.
