### ISSUE TITLE
Regression: `settings` fixture breaks with django-appconfig

### ISSUE THREAD

**Issue by julen** [pytest-dev/pytest-django#557]
I had the need to use the _new_ `settings` fixture (from #324, thanks for that btw!) in order to write some timezone-related tests, so I upgraded from 3.0.0 to 3.1.2, wrote the tests and all looked fine when run in isolation.

However, when running the entire test suite, some view tests that render templates and use [django-statici18n](https://github.com/zyegfryed/django-statici18n) (which in turn uses [django-appconf](https://github.com/django-compressor/django-appconf/)) are now breaking. The reason for the breakage is that default settings from statici18n cannot be found, i.e. those settings which I don't explicitly set but should be handled automatically by django-appconf, e.g.

```py
...
  File ".../lib/python2.7/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File ".../lib/python2.7/site-packages/statici18n/templatetags/statici18n.py", line 33, in statici18n
    return static(get_path(locale))
  File ".../lib/python2.7/site-packages/statici18n/templatetags/statici18n.py", line 21, in get_path
    get_filename(locale, settings.STATICI18N_DOMAIN))
  File ".../lib/python2.7/site-packages/statici18n/utils.py", line 27, in get_filename
    (settings.STATICI18N_FILENAME_FUNCTION, e))
  File ".../lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'STATICI18N_FILENAME_FUNCTION'
```

My current workaround is manually setting the defaults that are missing, although my expectation would be for it to work transparently as it did in pytest-django 3.0.0 and below.

**Comment by blueyed** [comment]
Can you git-bisect it?
Is the merge (https://github.com/pytest-dev/pytest-django/commit/54650ea556af0eda5dd5b95f727ccef603c7da47) breaking it for you?
Can you provide steps (or a failing test for pytest-django) to reproduce it?

**Comment by julen** [comment]
Yes, git bisect points at that commit:

```git
54650ea556af0eda5dd5b95f727ccef603c7da47 is the first bad commit
commit 54650ea556af0eda5dd5b95f727ccef603c7da47
Author: Denis Cornehl <denis.cornehl@gmail.com>
Date:   Mon Nov 7 13:22:08 2016 +0100

    Fixed #136 - fix the settings fixture for certain settings. (#324)

:040000 040000 f01585f1cb7df98ab35a7eadb108f9e9ee0e169f 6c865d695e4ab3bb8582a17c986d47ac096c72fa M	pytest_django
:040000 040000 0767997beaa4d5991804debb7ddc0acaf895ce78 73c4e53e2055f75ce508b655650991ece80985c6 M	tests
```

I am not familiar with django-appconfig's internals (nor with the new `setting` fixture), so I'm afraid I won't be able to immediately provide a minimal test case which doesn't involve pulling django-appconfig as a dependency.

**Comment by julen** [comment]
Ok, I started looking at the internals and figured out this is due to the switch to Django's own `override_settings` helper, and the issue happens because statici18n's `AppConf` (from django-appconf) is not loaded early enough, so it cannot patch the proper settings module.

This was [already reported to django-appconf](https://github.com/django-compressor/django-appconf/issues/30#issuecomment-195374791) and the solution is to use Django's `AppConfig` for initializing statici18n's `AppConf`. So it's a bug in statici18n — I'll make a PR there and close this one.

**Comment by blueyed** [comment]
Thank you!

**Comment by jedie** [comment]
> So it's a bug in statici18n — I'll make a PR there and close this one.

Can to post a link to issues there?
Maybe it's related to my problem here: https://github.com/matthewwithanm/django-imagekit/issues/251
